spring:
  h2:
    console.enabled: true
  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    virtualHost: lbozpljt
    username: ${username}
    password: ${password}
  application:
    name: vendas-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
filas:
    atualizar: atualizar
server:
    port: 50000
eureka:
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
